### ISSUE TITLE
endpoints error x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#105]
Note by @mangelajo :  my interpretation on the bug is that an update on the "Submariner" resource wont result on the update of the deployment/daemonset/pods configuration, hence leaving old CAs/endpoints around. We need to ensure that changes on the operator resource update the deployment

After running subctl join, I'm seeing: 
Error while retrieving endpoints Get https://api.nmanos-cluster-a.devcluster.openshift.com:6443/apis/submariner.io/v1/endpoints: x509: certificate signed by unknown authority.

Maybe there's a different CA used inside the cluster verses the CA used for access outside the cluster?

Seems like similar error as in: https://github.com/kubernetes-sigs/kubefed/issues/1123

```
[nmanos@nmanos submariner-operator]$ kubconf_a  subctl deploy-broker --clusterid subm-cluster-a
* Deploying broker
Writing submariner broker data to broker-info.subm


[nmanos@nmanos submariner-operator]$ kubconf_a  oc get crds | grep submariner
clusters.submariner.io                                      2019-12-17T15:25:02Z
endpoints.submariner.io                                     2019-12-17T15:25:02Z


[nmanos@nmanos submariner-operator]$ kubconf_a  subctl join --clusterid subm-cluster-a ./broker-info.subm --ikeport 501 --nattport 4501
* ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
* There are 1 labeled nodes in the cluster:
  - ip-10-0-28-151.ec2.internal
* Deploying the submariner operator
* Created operator CRDs.
* Created operator namespace: submariner-operator
* Created operator service account and role
* Updated the privileged SCC
* Deployed the operator successfully
* The operator is up and running
* Discovering network details
    Discovered network details:
        Network plugin:  OpenShift
        ClusterIP CIDRs: [172.30.0.0/16]
        Pod CIDRs:       [10.128.0.0/14]
* Deploying Submariner
* Submariner is up and running
[nmanos@nmanos submariner-operator]$ kubconf_a  oc get crds | grep submariner
clusters.submariner.io                                      2019-12-17T15:25:02Z
endpoints.submariner.io                                     2019-12-17T15:25:02Z
submariners.submariner.io                                   2019-12-17T15:26:32Z





[nmanos@nmanos submariner-operator]$ kubconf_a  oc get namespace submariner-operator -o json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "openshift.io/sa.scc.mcs": "s0:c23,c7",
            "openshift.io/sa.scc.supplemental-groups": "1000520000/10000",
            "openshift.io/sa.scc.uid-range": "1000520000/10000"
        },
        "creationTimestamp": "2019-12-17T15:26:32Z",
        "name": "submariner-operator",
        "resourceVersion": "79024",
        "selfLink": "/api/v1/namespaces/submariner-operator",
        "uid": "9aaff8b4-20e1-11ea-9b4d-0a5d94a42edf"
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Active"
    }
}



[nmanos@nmanos submariner-operator]$   kubconf_a  oc get Submariner -n submariner-operator -o yaml
apiVersion: v1
items:
- apiVersion: submariner.io/v1alpha1
  kind: Submariner
  metadata:
    creationTimestamp: "2019-12-17T15:26:49Z"
    generation: 1
    name: submariner
    namespace: submariner-operator
    resourceVersion: "79183"
    selfLink: /apis/submariner.io/v1alpha1/namespaces/submariner-operator/submariners/submariner
    uid: a5348ee7-20e1-11ea-9b4d-0a5d94a42edf
  spec:
    broker: k8s
    brokerK8sApiServer: api.nmanos-cluster-a.devcluster.openshift.com:6443
    brokerK8sApiServerToken: ""
    brokerK8sCA: ""
    brokerK8sRemoteNamespace: ""
    ceIPSecDebug: false
    ceIPSecIKEPort: 501
    ceIPSecNATTPort: 4501
    ceIPSecPSK: RmdnYry5pgLJuAUy12GfiR/38FOXLHBcUg5+E/FjVNVZRXH+8Hy9ABROdxuiZYia
    clusterCIDR: 10.128.0.0/14
    clusterID: subm-cluster-a
    colorCodes: blue
    count: 0
    debug: false
    namespace: submariner-operator
    natEnabled: true
    repository: quay.io/submariner
    serviceCIDR: 172.30.0.0/16
    version: 0.0.3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""


[nmanos@nmanos submariner-operator]$ kubconf_b subctl join --clusterid subm-cluster-b ./broker-info.subm --ikeport 501 --nattport 4501
* ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
* There are 1 labeled nodes in the cluster:
  - nmanos-cl2-tsdqz-worker-l5cb9
* Deploying the submariner operator
* Created operator CRDs.
* Created operator namespace: submariner-operator
* Created operator service account and role
* Deployed the operator successfully
* The operator is up and running
* Discovering network details
    Discovered network details:
        Network plugin:  OpenShift
        ClusterIP CIDRs: [100.96.0.0/16]
        Pod CIDRs:       [10.252.0.0/14]
* Deploying Submariner
* Submariner is up and running



[nmanos@nmanos submariner-operator]$ kubconf_b  oc get crds | grep submariner
clusters.submariner.io                                      2019-12-17T15:29:58Z
endpoints.submariner.io                                     2019-12-17T15:29:58Z
submariners.submariner.io                                   2019-12-17T15:29:36Z


[nmanos@nmanos submariner-operator]$   kubconf_b  oc get namespace submariner-operator -o json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "openshift.io/sa.scc.mcs": "s0:c23,c12",
            "openshift.io/sa.scc.supplemental-groups": "1000530000/10000",
            "openshift.io/sa.scc.uid-range": "1000530000/10000"
        },
        "creationTimestamp": "2019-12-17T15:29:36Z",
        "name": "submariner-operator",
        "resourceVersion": "4912097",
        "selfLink": "/api/v1/namespaces/submariner-operator",
        "uid": "086121d4-20e2-11ea-89a8-fa163e114f71"
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Active"
    }
}


[nmanos@nmanos submariner-operator]$   kubconf_b  oc get Submariner -n submariner-operator -o yaml
apiVersion: v1
items:
- apiVersion: submariner.io/v1alpha1
  kind: Submariner
  metadata:
    creationTimestamp: "2019-12-17T15:29:58Z"
    generation: 1
    name: submariner
    namespace: submariner-operator
    resourceVersion: "4912256"
    selfLink: /apis/submariner.io/v1alpha1/namespaces/submariner-operator/submariners/submariner
    uid: 15bd618d-20e2-11ea-89a8-fa163e114f71
  spec:
    broker: k8s
    brokerK8sApiServer: api.nmanos-cluster-a.devcluster.openshift.com:6443
    brokerK8sApiServerToken: ""
    brokerK8sCA: ""
    brokerK8sRemoteNamespace: ""
    ceIPSecDebug: false
    ceIPSecIKEPort: 501
    ceIPSecNATTPort: 4501
    ceIPSecPSK: RmdnYry5pgLJuAUy12GfiR/38FOXLHBcUg5+E/FjVNVZRXH+8Hy9ABROdxuiZYia
    clusterCIDR: 10.252.0.0/14
    clusterID: subm-cluster-b
    colorCodes: blue
    count: 0
    debug: false
    namespace: submariner-operator
    natEnabled: true
    repository: quay.io/submariner
    serviceCIDR: 100.96.0.0/16
    version: 0.0.3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""



[nmanos@nmanos submariner-operator]$ op_pod_a=$(kubconf_a oc get pod -n submariner-operator -l app=submariner-engine -o jsonpath="{.items[0].metadata.name}")
[nmanos@nmanos submariner-operator]$   kubconf_a oc exec $op_pod_a -n submariner-operator strongswan status
error: unable to upgrade connection: container not found ("submariner")


[nmanos@nmanos submariner-operator]$ kubconf_a oc logs $op_pod_a -n submariner-operator
+ trap 'exit 1' SIGTERM SIGINT
+ export CHARON_PID_FILE=/var/run/charon.pid
+ CHARON_PID_FILE=/var/run/charon.pid
+ rm -f /var/run/charon.pid
+ '[' false == true ']'
+ DEBUG=-v=4
+ mkdir -p /etc/ipsec
+ sysctl -w net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.all.send_redirects = 0
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/libexec/strongswan
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/libexec/strongswan
+ exec submariner-engine -v=4 -alsologtostderr
I1217 15:30:27.917421       1 main.go:51] Starting submariner
W1217 15:30:27.918131       1 client_config.go:551] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1217 15:30:27.921895       1 merged_client_builder.go:159] Using in-cluster namespace
I1217 15:30:27.921941       1 main.go:187] Using namespace submariner-operator for the leader election lock
I1217 15:30:27.921958       1 leaderelection.go:205] attempting to acquire leader lease  submariner-operator/submariner-engine-lock...
I1217 15:30:27.946285       1 leaderelection.go:214] successfully acquired lease submariner-operator/submariner-engine-lock
I1217 15:30:27.946508       1 event.go:221] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"submariner-operator", Name:"submariner-engine-lock", UID:"b674d6f8-20e1-11ea-9b4d-0a5d94a42edf", APIVersion:"v1", ResourceVersion:"80257", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' ip-10-0-28-151-submariner-engine became leader
I1217 15:30:28.022579       1 tunnel.go:41] Setting up event handlers
I1217 15:30:28.022976       1 main.go:131] Starting controllers
I1217 15:30:28.023020       1 datastoresyncer.go:132] Starting the DatastoreSyncer
I1217 15:30:28.023031       1 datastoresyncer.go:133] Waiting for informer caches to sync
I1217 15:30:28.023158       1 tunnel.go:57] Starting Tunnel Controller
I1217 15:30:28.023173       1 tunnel.go:60] Waiting for informer caches to sync
I1217 15:30:28.023238       1 reflector.go:122] Starting reflector *v1.Endpoint (30s) from github.com/submariner-io/submariner/pkg/client/informers/externalversions/factory.go:117
I1217 15:30:28.023266       1 reflector.go:160] Listing and watching *v1.Endpoint from github.com/submariner-io/submariner/pkg/client/informers/externalversions/factory.go:117
I1217 15:30:28.023341       1 reflector.go:122] Starting reflector *v1.Cluster (30s) from github.com/submariner-io/submariner/pkg/client/informers/externalversions/factory.go:117
I1217 15:30:28.023355       1 reflector.go:160] Listing and watching *v1.Cluster from github.com/submariner-io/submariner/pkg/client/informers/externalversions/factory.go:117
I1217 15:30:28.023441       1 ipsec.go:38] Starting IPSec Engine (Charon)
I1217 15:30:28.024094       1 strongswan.go:422] Starting Charon
I1217 15:30:28.123260       1 shared_informer.go:123] caches populated
I1217 15:30:28.123288       1 datastoresyncer.go:77] Ensuring we are the only endpoint active for this cluster
I1217 15:30:28.124064       1 shared_informer.go:123] caches populated
I1217 15:30:28.124081       1 tunnel.go:65] Starting workers
I1217 15:30:28.124095       1 tunnel.go:68] Started workers
F1217 15:30:28.142124       1 datastoresyncer.go:80] Error while retrieving endpoints Get https://api.nmanos-cluster-a.devcluster.openshift.com:6443/apis/submariner.io/v1/endpoints: x509: certificate signed by unknown authority
goroutine 59 [running]:
k8s.io/klog.stacks(0xc000242200, 0xc0003801c0, 0xe4, 0x1b5)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:828 +0xb1
k8s.io/klog.(*loggingT).output(0x1e32e80, 0xc000000003, 0xc0000f60e0, 0x1dc3edd, 0x12, 0x50, 0x0)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:779 +0x2d9
k8s.io/klog.(*loggingT).printf(0x1e32e80, 0xc000000003, 0x129ad73, 0x23, 0xc0000e3b28, 0x1, 0x1)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:678 +0x14e
k8s.io/klog.Fatalf(...)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:1207
github.com/submariner-io/submariner/pkg/controllers/datastoresyncer.(*DatastoreSyncer).ensureExclusiveEndpoint(0xc0000b0ea0)
	/go/src/github.com/submariner-io/submariner/pkg/controllers/datastoresyncer/datastoresyncer.go:80 +0x8d7
github.com/submariner-io/submariner/pkg/controllers/datastoresyncer.(*DatastoreSyncer).Run(0xc0000b0ea0, 0xc00008a6c0, 0x0, 0x0)
	/go/src/github.com/submariner-io/submariner/pkg/controllers/datastoresyncer/datastoresyncer.go:138 +0x29e
main.main.func1.3(0xc0002e4270, 0xc0000b0ea0, 0xc00008a6c0, 0xc00008c9b0)
	/go/src/github.com/submariner-io/submariner/main.go:151 +0x63
created by main.main.func1
	/go/src/github.com/submariner-io/submariner/main.go:149 +0xaac

```

**Comment by mangelajo** [comment]
That probably happens if you are using an old .subm file to join a new broker... it happened to me once.

Probably something we can do before configuring a cluster with a subm file... is checking that the credentials are still valid.

**Comment by manosnoam** [comment]
How do we get an updated `broker-info.subm` file ? 
I can't find it in the repository.

**Comment by skitt** [comment]
`broker-info.subm` is generated by `subctl deploy-broker`.

**Comment by manosnoam** [comment]
@skitt  well I did run it befor the join command:
```
subctl deploy-broker --clusterid subm-cluster-a
* Deploying broker
Writing submariner broker data to broker-info.subm
```

**Comment by manosnoam** [comment]
I've deleted `broker-info.subm` and re-run subctl commands... still got same error:
`error: unable to upgrade connection: container not found ("submariner")`

[endpoints error x509 certificate signed by unknown authority 2.txt](https://github.com/submariner-io/submariner-operator/files/3983141/endpoints.error.x509.certificate.signed.by.unknown.authority.2.txt)

**Comment by skitt** [comment]
> @skitt well I did run it before the join command:
> 
> ```
> subctl deploy-broker --clusterid subm-cluster-a
> * Deploying broker
> Writing submariner broker data to broker-info.subm
> ```

Yeah, I’m not saying you didn’t, just answering your question about how to get an updated `broker-info.subm` file ;-).

**Comment by manosnoam** [comment]
This issue is being reproduced on my environment many times.
It blocks Submariner communication between clusters.

On the private cluster (OSP) I'm seeing in the submariner-engine pod:

github.com/submariner-io/submariner/pkg/client/informers/externalversions/factory.go:117:
Failed to list *v1.Endpoint: Get https://api.nmanos-cluster-a.devcluster.openshift.com:6443/apis/submariner.io/v1/namespaces/submariner-k8s-broker/endpoints?limit=500&resourceVersion=0:
x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer")

Full console output.
[submariner_test_06012020_1338.log](https://github.com/submariner-io/submariner-operator/files/4029865/submariner_test_06012020_1338.log)

**Comment by manosnoam** [comment]
Looking at SubM crds, I see that it was only updated on Cluster A (AWS):

[nmanos@nmanos ocp-install]$ kubconf_a oc get crd | grep subm
clusters.submariner.io                                      2020-01-06T12:17:06Z
endpoints.submariner.io                                     2020-01-06T12:17:06Z
submariners.submariner.io                                   2020-01-06T12:17:10Z

But not on Cluster B (OSP) it is one week old:

[nmanos@nmanos ocp-install]$ kubconf_b oc get crd | grep subm
clusters.submariner.io                                      2019-12-31T11:06:18Z
endpoints.submariner.io                                     2019-12-31T11:06:18Z
submariners.submariner.io                                   2019-12-31T11:06:01Z

Removing these CRDs, and running subct join agai, has solved the issue!

Perhaps it is required to alert when joining a Cluster that already have previous SubM CRDs installed ?

**Comment by mangelajo** [comment]
@manosnoam can you show us how to reproduce it step by step?

We need to fix this but I don't get to reproduce the issue.

**Comment by mangelajo** [comment]
We need to verify the service configuration update history, @tpantelis told he me was looking at this, if not I can look at it.

**Comment by mangelajo** [comment]
@tpantelis added you to this issue (related to the changes in Submariner crd propagation to daemonsets, etc..) . If you are busy on other stuff I can handle it too, switch the issue to me in that case.

**Comment by manosnoam** [comment]
> @manosnoam can you show us how to reproduce it step by step?
> 
> We need to fix this but I don't get to reproduce the issue.

Please see this error reproduced today. Attaching console output:
[submariner_test_28012020_1714.log](https://github.com/submariner-io/submariner-operator/files/4127018/submariner_test_28012020_1714.log)

**Comment by mangelajo** [comment]
Ack,

I suspect it’s just an issue on updating a pre-existing deployment to connect to a newly deployed broker.

**Comment by manosnoam** [comment]
[Here's](https://github.com/submariner-io/submariner-operator/files/4128828/endpoints.error.x509.certificate.signed.by.unknown.authority.3.txt) output of:
```
kubectl get Submariner -o yaml
kubectl get deployments -o yaml -n submariner-operator
kubectl get pods -o yaml -n submariner-operator
```
On each cluster.
