### ISSUE TITLE
subctl benchmark throughput and latency does not work with wireguard

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#1279]
**What happened**:
`subctl benchmark throughput output/kubeconfigs/kind-config-cluster2 output/kubeconfigs/kind-config-cluster3 --verbose`
`subctl benchmark latency output/kubeconfigs/kind-config-cluster2 output/kubeconfigs/kind-config-cluster3 --verbose`
 fails with error
```
$ subctl benchmark throughput output/kubeconfigs/kind-config-cluster2 output/kubeconfigs/kind-config-cluster3 --verbose
Performing throughput tests
Creating kubernetes clients
Creating lighthouse clients
panic: Failed to find Clusters to detect if Globalnet is enabled. No Cluster found
Unexpected error:
    <*errors.errorString | 0xc0002bc1b0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred

goroutine 1 [running]:
github.com/submariner-io/submariner-operator/pkg/subctl/benchmark.StartLatencyTests.func1(0xc0000fac00, 0xf2, 0xc0005be9f0, 0x1, 0x1)
	github.com/submariner-io/submariner-operator/pkg/subctl/benchmark/latency.go:44 +0x6b
github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc0000c7cc0, 0x19ba860, 0x242f700, 0x0, 0xc0003eb670, 0x1, 0x1, 0x169)
	github.com/onsi/gomega@v1.11.0/internal/assertion/assertion.go:79 +0x216
github.com/onsi/gomega/internal/assertion.(*Assertion).NotTo(0xc0000c7cc0, 0x19ba860, 0x242f700, 0xc0003eb670, 0x1, 0x1, 0xc000112000)
	github.com/onsi/gomega@v1.11.0/internal/assertion/assertion.go:48 +0xc7
github.com/submariner-io/shipyard/test/e2e/framework.AwaitUntil(0x17f34aa, 0x2f, 0xc000673af8, 0x18880b0, 0xc00007e460, 0x17bafde)
	github.com/submariner-io/shipyard@v0.9.0-rc0/test/e2e/framework/framework.go:488 +0x1c6
github.com/submariner-io/shipyard/test/e2e/framework.DetectGlobalnet()
	github.com/submariner-io/shipyard@v0.9.0-rc0/test/e2e/framework/framework.go:228 +0x10e
github.com/submariner-io/lighthouse/test/e2e/framework.beforeSuite()
	github.com/submariner-io/lighthouse@v0.9.0-rc0/test/e2e/framework/framework.go:88 +0x247
github.com/submariner-io/shipyard/test/e2e/framework.BeforeSuite()
	github.com/submariner-io/shipyard@v0.9.0-rc0/test/e2e/framework/framework.go:184 +0x5c2
github.com/submariner-io/submariner-operator/pkg/subctl/benchmark.initFramework(0x17b9cf0, 0x7, 0x19)
	github.com/submariner-io/submariner-operator/pkg/subctl/benchmark/throughput.go:90 +0xa5
github.com/submariner-io/submariner-operator/pkg/subctl/benchmark.StartLatencyTests(0x1993000)
	github.com/submariner-io/submariner-operator/pkg/subctl/benchmark/latency.go:47 +0xab
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.testLatency(0x23d45c0, 0xc000373410, 0x2, 0x3)
	github.com/submariner-io/submariner-operator/pkg/subctl/cmd/benchmark.go:95 +0x5d
github.com/spf13/cobra.(*Command).execute(0x23d45c0, 0xc0003733b0, 0x3, 0x3, 0x23d45c0, 0xc0003733b0)
	github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x23d52e0, 0x445bca, 0x22dc9a0, 0xc000064778)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
	github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:56
main.main()
	command-line-arguments/main.go:27 +0x32
```

**What you expected to happen**:
Commands to work properly

**How to reproduce it (as minimally and precisely as possible)**:
Run above commands with cabledriver as wireguard

**Environment**:
- Submariner version (use `subctl version`): 0.9-rc1

**Comment by Jaanki** [comment]
`submariner-gateway-6bm9h                        0/1     CrashLoopBackOff   15         55m`

This seems to be an issue

**Comment by nyechiel** [comment]
@Jaanki did you manage to bring the pod up? I suggest we close this bug and report a new one if there is an issue with WireGuard and/or the `submariner-gateway` pod, otherwise the title of this Issue is misleading.

**Comment by Jaanki** [comment]
The GW pod was crashing and hence the failing benchmark tests.

Raised another issue https://github.com/submariner-io/submariner/issues/1281 to track pod crashing. Closing this one.
