### ISSUE TITLE
subctl show connections panics sometimes

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#1497]
**What happened**:

subctl show connections exploded on CI:

https://github.com/submariner-io/submariner-operator/runs/3110537042?check_suite_focus=true#step:3:858

```
 • Showing Connections  ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1a02ca9]

goroutine 1 [running]:
github.com/submariner-io/submariner-operator/pkg/subctl/cmd/show.getConnectionsStatus(0xc000114050, 0xc000538ea0)
	github.com/submariner-io/submariner-operator/pkg/subctl/cmd/show/connections.go:65 +0x89
github.com/submariner-io/submariner-operator/pkg/subctl/cmd/show.showConnections(0xc000114050, 0xc0002cf208)
	github.com/submariner-io/submariner-operator/pkg/subctl/cmd/show/connections.go:132 +0x3f
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.ExecuteMultiCluster(0x1fe2f30)
	github.com/submariner-io/submariner-operator/pkg/subctl/cmd/execute.go:103 +0x1a7
github.com/submariner-io/submariner-operator/pkg/subctl/cmd/show.init.1.func1(0xc000220580, 0x30541c8, 0x0, 0x0)
	github.com/submariner-io/submariner-operator/pkg/subctl/cmd/show/connections.go:49 +0x2d
github.com/spf13/cobra.(*Command).execute(0xc000220580, 0x30541c8, 0x0, 0x0, 0xc000220580, 0x30541c8)
	github.com/spf13/cobra@v1.2.0/command.go:863 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2ff79a0, 0x30256c0, 0x0, 0xc000060778)
	github.com/spf13/cobra@v1.2.0/command.go:977 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.0/command.go:905
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
	github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:58
main.main()
	command-line-arguments/main.go:31 +0x32
iter: 1. Clusters not yet connected. sleeping for 6 secs
```
**What you expected to happen**:

subctl should not panic

**Comment by tpantelis** [comment]
This is due to a recent change - `GetGateways` can return `nil, nil` if `List` returns `NotFound` due to CRD not yet installed.
