### ISSUE TITLE
subctl fails to update existing Submariner CRs

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#49]
Running `join` on a cluster where a Submariner CR already exists results in

```
* Deploying Submariner
panic: submariners.submariner.io "submariner" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

goroutine 1 [running]:
github.com/submariner-io/submariner-operator/pkg/subctl/operator/deploy.Ensure(0xc00000a960, 0x1353ffa, 0x13, 0x7ffdb84a4887, 0x5, 0x7ffdb84a4897, 0x5, 0x7ffdb84a4871, 0x8, 0xc00042852b, ...)
	/home/skitt/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/operator/deploy/ensure.go:105 +0x1166
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.joinSubmarinerCluster(0xc0004dd180)
	/home/skitt/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:86 +0x31f
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.glob..func2(0x1e4e720, 0xc00001d080, 0x1, 0xb)
	/home/skitt/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:60 +0x225
github.com/spf13/cobra.(*Command).execute(0x1e4e720, 0xc00001cfd0, 0xb, 0xb, 0x1e4e720, 0xc00001cfd0)
	/home/skitt/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1e4e9a0, 0x0, 0x11638a0, 0xc000054118)
	/home/skitt/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/skitt/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
	/home/skitt/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:34
main.main()
	/home/skitt/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/main.go:6 +0x2e
```

**Comment by mangelajo** [comment]
Yes, that happened to me for other resource, you need to get the existing one, update fields, then push it back, or just take the old resource version & uuid in metadata and move it into the new config before updating

**Comment by mangelajo** [comment]
This was fixed by: https://github.com/submariner-io/submariner-operator/pull/79

**Comment by manosnoam** [comment]
It seems to be related to an older bug: https://github.com/submariner-io/submariner/issues/242 
Where we also got "Invalid value: 0x0: must be specified for an update"
