### ISSUE TITLE
subctl join runtime error

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#560]
```
08:31:40 (conda-test) subctl join --clusterid nmanos-cluster-b   ./broker-info.subm    --ikeport 501 --nattport 4501 --subm-debug
08:31:40 * ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
08:31:40 * There are 1 labeled nodes in the cluster:
08:31:40   - default-cl1-6qxw4-worker-gldcn
08:31:40  ��� Discovering network details  ...
08:31:40     Discovered network details:
08:31:40         Network plugin:  OpenShift
08:31:40         Service CIDRs:   [100.96.0.0/16]
08:31:40         Cluster CIDRs:   [10.252.0.0/14]
08:31:40  ��� Discovering network details
08:31:40  ��� Discovering multi cluster details  ...
08:31:40  ��� Validating Globalnet configurations  ...
08:31:40  ��� Validating Globalnet configurations
08:31:40  ��� Assigning Globalnet IPs  ...
08:31:40 panic: runtime error: invalid memory address or nil pointer dereference
08:31:40 [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x10fd5c3]
08:31:40 
08:31:40 goroutine 1 [running]:
08:31:40 github.com/submariner-io/submariner-operator/pkg/discovery/globalnet.NewCIDR(0x0, 0x0, 0xc0002d5410, 0x10, 0x10)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/pkg/discovery/globalnet/globalnet.go:91 +0x43
08:31:40 github.com/submariner-io/submariner-operator/pkg/discovery/globalnet.AllocateGlobalCIDR(0xc000ad30e0, 0xc000ad31a0, 0x7ffc8d9707bd, 0x10, 0x24dec00)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/pkg/discovery/globalnet/globalnet.go:166 +0x161
08:31:40 github.com/submariner-io/submariner-operator/pkg/discovery/globalnet.AssignGlobalnetIPs(0xc000ad30e0, 0x0, 0x0, 0x0, 0xc00091cdc0, 0xd, 0x1, 0xc00091cc70, 0xd, 0x1, ...)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/pkg/discovery/globalnet/globalnet.go:335 +0xfd
08:31:40 github.com/submariner-io/submariner-operator/pkg/subctl/cmd.AllocateAndUpdateGlobalCIDRConfigMap.func1(0xc0002b2510, 0x1697c66)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:249 +0x2fd
08:31:40 k8s.io/client-go/util/retry.RetryOnConflict.func1(0x100000000, 0x1697c66, 0xd)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/vendor/k8s.io/client-go/util/retry/util.go:64 +0x33
08:31:40 k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc0002d5868, 0xc000c4da60, 0x1)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:265 +0x51
08:31:40 k8s.io/client-go/util/retry.RetryOnConflict(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc0002d58d0, 0x0, 0xc0002d58f8)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/vendor/k8s.io/client-go/util/retry/util.go:63 +0x8f
08:31:40 github.com/submariner-io/submariner-operator/pkg/subctl/cmd.AllocateAndUpdateGlobalCIDRConfigMap(0xc0001c1b80, 0xc000a18360, 0x15, 0xc0002d5b40, 0xc000a18360, 0x15)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:237 +0xcb
08:31:40 github.com/submariner-io/submariner-operator/pkg/subctl/cmd.joinSubmarinerCluster(0xc0001d61e0, 0xc0002b3080)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:201 +0x39f
08:31:40 github.com/submariner-io/submariner-operator/pkg/subctl/cmd.glob..func2(0x248b300, 0xc000706500, 0x1, 0x8)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:114 +0x27f
08:31:40 github.com/spf13/cobra.(*Command).execute(0x248b300, 0xc000706400, 0x8, 0x8, 0x248b300, 0xc000706400)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:842 +0x29d
08:31:40 github.com/spf13/cobra.(*Command).ExecuteC(0x248b060, 0x442c5a, 0x23907e0, 0xc000146778)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:943 +0x317
08:31:40 github.com/spf13/cobra.(*Command).Execute(...)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:883
08:31:40 github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:53
08:31:40 main.main()
08:31:40 	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/main.go:27 +0x32
08:31:41 cat: /tmp/evErr.28812.log: No such file or directory
08:31:41 +++ exit code: 1
08:31:41 +++ error: 1
```

Full test report:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/740/Test-Report/

**Comment by mangelajo** [comment]
How do you reproduce this?

**Comment by manosnoam** [comment]
Thanks for pinging me @mangelajo 
I'm closing this, it was not reproduced since then.
