### ISSUE TITLE
Any k8s > 1.14 will not work, we need to update the operator CRD definitions to work with newer k8s versions

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#66]

**Comment by mangelajo** [comment]
Working on this, and hitting some issues with the operator-sdk / codegen:

```INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [submariner:[v1alpha1], ]
F1203 09:36:18.108072      21 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from github.com/submariner-io/submariner-operator/pkg/apis/submariner/v1alpha1.Submariner
goroutine 1 [running]:
k8s.io/klog.stacks(0xc00071bf00, 0xc00050c120, 0xc0, 0x110)
        /home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:855 +0xb8
k8s.io/klog.(*loggingT).output(0x335c940, 0xc000000003, 0xc000160d20, 0x3146640, 0xb, 0x375, 0x0)
        /home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:806 +0x351
k8s.io/klog.(*loggingT).printf(0x335c940, 0x3, 0x1ee9b04, 0x2a, 0xc0006beed8, 0x3, 0x3)
        /home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:705 +0x14b

Any hints on why could this be happening?
I'm running # operator-sdk generate k8s
```

**Comment by mangelajo** [comment]
https://github.com/kubernetes/gengo/blob/7fa3014cb28f99ce2d9e803bcd3efa7edd4effa9/examples/deepcopy-gen/generators/deepcopy.go#L885

hmm
It's hitting that, but why any of my types is invalid?
I have only normal stuff like string, int, bool, int32

**Comment by mangelajo** [comment]
Ok, I opened a bug to operator-sdk: 

https://github.com/operator-framework/operator-sdk/issues/2288

It happens out of the box..

**Comment by mangelajo** [comment]
ok the secret to make operator-sdk work fine was setting GOROOT

**Comment by mangelajo** [comment]
Based on my testing this works now:

Before:
```
 ./subctl-v0.0.2-linux-amd64 join broker-info.subm 
* broker-info.subm says broker is at: https://xxxxx:6443
? What is your cluster ID? k3s-ovh1
There are 1 nodes in the cluster
? Which node should be used as the gateway? k3s-test2
* Deploying the submariner operator
panic: CustomResourceDefinition.apiextensions.k8s.io "submariners.submariner.io" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc011817030), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00a7d7920), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc011817030), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00a7d7920), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version subresources may not all be set to identical values (top-level subresources should be used instead)]
```
After:
```
$ ./subctl-v0.0.3-linux-amd64 join broker-info.subm 
* broker-info.subm says broker is at: https://xxxx:6443
? What is your cluster ID? k3s-ovh-1
* There are 1 labeled nodes in the cluster:
  - k3s-test2
* Deploying the submariner operator
* Created operator CRDs.
* Created operator namespace: submariner-operator
* Created operator service account and role
* Deploying the operator...

```
