### ISSUE TITLE
Operator Pod Crashing when submariner is redeployed

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner-operator#692]
The operator pod is crashing when submariner is redeployed after cleaning up with this error
```

,"Deployment.Namespace":"submariner-operator","Deployment.Name":"submariner-lighthouse-coredns"}
{"level":"info","ts":1599743885.902029,"logger":"controller_servicediscovery","msg":"ClusterIP of Lighthouse DNS server changed, hence updating Cluster DNS Operator CR","Request.Namespace":"submariner-operator","Request.Name":"service-discovery"}
E0910 13:18:05.902192       1 runtime.go:78] Observed a panic: runtime.boundsError{x:2, y:1, signed:true, code:0x3} (runtime error: slice bounds out of range [2:1])
goroutine 1754 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16b8180, 0xc000c069e0)
	submariner-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	submariner-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x16b8180, 0xc000c069e0)
	/usr/lib/golang/src/runtime/panic.go:969 +0x166
github.com/submariner-io/submariner-operator/pkg/controller/servicediscovery.updateOpenshiftClusterDNSOperator.func1(0xc000e35a88, 0x1208a72)
	submariner-operator/pkg/controller/servicediscovery/servicediscovery_controller.go:431 +0xceb
k8s.io/client-go/util/retry.OnError.func1(0xc000e35ab0, 0x1207ac1, 0x0)
	submariner-operator/vendor/k8s.io/client-go/util/retry/util.go:51 +0x3c
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000e35b10, 0x0, 0xc000e35b20)
	submariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/util/retry.OnError(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0x1864570, 0xc000e35bb0, 0x1864570, 0xc000e35bc0)
	submariner-operator/vendor/k8s.io/client-go/util/retry/util.go:50 +0xa6
k8s.io/client-go/util/retry.RetryOnConflict(...)
	submariner-operator/vendor/k8s.io/client-go/util/retry/util.go:104
github.com/submariner-io/submariner-operator/pkg/controller/servicediscovery.updateOpenshiftClusterDNSOperator(0xc00012a4e0, 0x1a16520, 0xc0008fbc50, 0x1a16580, 0xc0001ce4b0, 0x1a0e0c0, 0xc000df7aa0, 0x19d6b40, 0xc00044c900)
	submariner-operator/pkg/controller/servicediscovery/servicediscovery_controller.go:408 +0x124
github.com/submariner-io/submariner-operator/pkg/controller/servicediscovery.(*ReconcileServiceDiscovery).Reconcile(0xc0001ce4e0, 0xc0007ef460, 0x13, 0xc0007ef440, 0x11, 0xc00082a240, 0xc00082b0e8, 0xc00082b0e0, 0xc00082b0e0)
	submariner-operator/pkg/controller/servicediscovery/servicediscovery_controller.go:169 +0x892
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0008a2580, 0x16235c0, 0xc0007c72a0, 0x0)
	submariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0008a2580, 0xc000205700)
	submariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0008a2580)
	submariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:201 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000dfacd0)
	submariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000dfacd0, 0x3b9aca00, 0x0, 0x1, 0xc000082420)
	submariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000dfacd0, 0x3b9aca00, 0xc000082420)
	submariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	submariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:183 +0x426
panic: runtime error: slice bounds out of range [2:1] [recovered]
	panic: runtime error: slice bounds out of range [2:1]

```

The issue seems to be modifying the endpoint slice once reduces its length and a second modification causes it to go out of bounds.

**Comment by manosnoam** [comment]
Verified on OCP as well.
